# Generated by Django 4.1.7 on 2023-04-17 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='product_inf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CampaignApp.product_information'),
        ),
    ]
