# Generated by Django 4.1.7 on 2023-04-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignApp', '0002_campaign_product_inf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='product_inf',
        ),
    ]
