# Generated by Django 4.1.7 on 2023-06-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignApp', '0002_transferdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='account_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
