# Generated by Django 4.1.7 on 2023-04-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignApp', '0003_remove_campaign_product_inf'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='influencer_fee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
