# Generated by Django 4.1.7 on 2023-06-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignApp', '0003_paymentdetails_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='salespaid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
