# Generated by Django 4.1.7 on 2023-06-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignApp', '0004_paymentdetails_salespaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='modashinfluencer',
            name='admin_approved',
            field=models.BooleanField(default=0),
        ),
    ]
