# Generated by Django 4.1.7 on 2023-04-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignApp', '0004_campaign_influencer_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='modashinfluencer',
            name='fullname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='modashinfluencer',
            name='isverified',
            field=models.BooleanField(null=True),
        ),
    ]
