# Generated by Django 4.1.7 on 2023-04-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignApp', '0006_campaign_influencerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='modashinfluencer',
            name='engagements',
            field=models.BigIntegerField(null=True),
        ),
    ]
