# Generated by Django 4.1.7 on 2023-04-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignApp', '0007_modashinfluencer_engagements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_information',
            name='coupon_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
