# Generated by Django 4.2.1 on 2023-07-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignApp', '0008_campaigncredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='payout_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product_information',
            name='coupon_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
