# Generated by Django 4.1.7 on 2023-05-01 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CampaignApp', '0009_modashinfluencer_influencerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign_accept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influencerid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='influencer_accept', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
