# Generated by Django 4.2.1 on 2023-07-25 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CampaignApp', '0012_paymentdetails_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerSalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('sales', models.FloatField(blank=True, null=True)),
                ('influencerfee', models.FloatField(blank=True, null=True)),
                ('offer', models.CharField(blank=True, max_length=200, null=True)),
                ('account_id', models.CharField(blank=True, max_length=200, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CampaignApp.campaign')),
                ('influencer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CampaignApp.modashinfluencer')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
