# Generated by Django 4.1.7 on 2023-05-01 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignApp', '0012_campaign_accept_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign_accept',
            old_name='status',
            new_name='campaign_status',
        ),
    ]
