# Generated by Django 4.2.1 on 2023-07-25 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignApp', '0013_influencersalesdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfluencerSalesData',
        ),
    ]
