# Generated by Django 4.1.7 on 2023-05-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignApp', '0014_campaign_accept_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign_accept',
            name='ModashInfluencer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
