# Generated by Django 4.2.1 on 2023-07-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignApp', '0014_delete_influencersalesdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripesubscription',
            name='amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
