# Generated by Django 4.1.7 on 2023-05-02 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignApp', '0015_campaign_accept_modashinfluencer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign_accept',
            old_name='ModashInfluencer',
            new_name='modashinfluencer',
        ),
    ]
