# Generated by Django 4.1.7 on 2023-05-02 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignApp', '0016_rename_modashinfluencer_campaign_accept_modashinfluencer'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_status', models.IntegerField(default=0)),
                ('campaignid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CampaignApp.campaign')),
                ('influencerid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CampaignApp.modashinfluencer')),
            ],
        ),
    ]
