# Generated by Django 4.1.7 on 2023-05-03 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignApp', '0021_notification_campaignid'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='influencerid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CampaignApp.modashinfluencer'),
        ),
    ]
