# Generated by Django 4.1.7 on 2023-04-10 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopifyApp', '0004_remove_coupon_rule_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
