# Generated by Django 4.2.1 on 2023-07-24 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripe_details',
            name='publishable_key',
        ),
        migrations.RemoveField(
            model_name='stripe_details',
            name='secret_key',
        ),
        migrations.AddField(
            model_name='stripe_details',
            name='account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stripe_details',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL),
        ),
    ]
