# Generated by Django 4.1.7 on 2023-06-01 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_stripe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stripe',
            new_name='stripe_details',
        ),
    ]
