# Generated by Django 4.1.7 on 2023-06-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_commission_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission_charges',
            name='commission',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
