# Generated by Django 4.1.7 on 2023-06-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_alter_commission_charges_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='shopify_url',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
