# Generated by Django 4.1.7 on 2023-04-12 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfluencerApp', '0005_influencerdetails_influencerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencerdetails',
            name='influencerid',
        ),
    ]
