# Generated by Django 4.1.7 on 2023-04-24 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InfluencerApp', '0006_remove_influencerdetails_influencerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerdetails',
            name='influencerid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
